# Generated by Django 2.1.1 on 2018-11-03 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20181103_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='e_mail',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custom_user',
            name='last_visted',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
