# Generated by Django 2.1.1 on 2018-11-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20181104_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
