# Generated by Django 2.1.1 on 2018-11-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20181103_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pictures',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='last_visted',
            field=models.DateTimeField(verbose_name='last visited'),
        ),
    ]
